site_name: The Great Crusty Custy Cook-Book

theme:
  name: material

  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true

extra:
  generator: false